#!/bin/sh

projectPath="${PROJECT_DIR}/PocketID"
modelPath="Model/Model.xcdatamodeld/Model.xcdatamodel"
classesPath="Model"
machineDir="Model/autogenerated"

echo "${PROJECT_DIR}"
echo $modelPath

# Mogenerator Location
if [ -x /usr/local/bin/mogenerator ]; then
  echo "mogenerator exists in /usr/local/bin path";
  MOGENERATOR_DIR="/usr/local/bin";
elif [ -x /usr/bin/mogenerator ]; then
  echo "mogenerator exists in /usr/bin path";
  MOGENERATOR_DIR="/usr/bin";
else
  echo "mogenerator not found"; exit 1;
fi

$MOGENERATOR_DIR/mogenerator -m "$projectPath/$modelPath" -O "$projectPath/$classesPath" -M "$projectPath/$machineDir" --template-var arc=true
